server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gate-way-service
  cloud:
    gateway:
      routes:
        - id:  address-service
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: webUi-service
          uri: lb://WEB-UI-SERVICE
          predicates:
            - Path=/web-ui/**,/bootstrap/**


